version: '3'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: moti
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: ./moti/
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./moti-app/
    ports:
      - "8080:8080"
    depends_on:
      - web

volumes:
  postgres_data:
